# containers
services:
  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1 # img do docker hub fornecida pelos tutores
    ports: # portas (container:host)
      - "9000:9000" # porta p/ api
      - "9090:9090" # porta p/ interface web
    environment: # variaveis. ex: usuario e senha
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes: # diretorios 
      - ./data_lake:/data

  metastore-db:
    image: postgres:15
    container_name: metastore-db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - metastore-data:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:4.0.1
    container_name: hive-metastore
    command: "hive --service metastore"
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_HOST: metastore-db
      HIVE_METASTORE_DB_PORT: 5432
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hive
      SERVICE_NAME: metastore
    depends_on:
      - metastore-db
    ports:
      - "9083:9083"

  trino:
    image: trinodb/trino
    ports:
      - "8080:8080" # web
    volumes:
      - ./trino/etc/catalog:/etc/trino/catalog

  trino-cli:
    image: trinodb/trino
    depends_on:
      - trino
    entrypoint: ["trino", "--server", "http://trino:8080", "--user", "mainero"]
    stdin_open: true
    tty: true
    
  # demais conteineres

  # metabase opcional
  # airflow-webserver
  # airflow-scheduler
  # airflor-db

volumes:
  metastore-data:
