# nao precisa da versao do compose; docker v2

# containers
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1 # img do docker hub fornecida pelos tutores
    ports: # portas (container:host)
      - "9000:9000" # porta p/ api
      - "9090:9090" # porta p/ interface web
    environment: # variaveis. ex: usuario e senha
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes: # diretorios do hd
      - ./data_lake:/data

  # demais conteineres

  # hive-metastore:
  #   image: apache/hive:4.0.0
  #   command: "hive --service metastore"
  #   ports:
  #     - "9083:9083"
  #   depends_on:
  #     - metastore-db
  #   environment:
  #     HIVE_METASTORE_DB_TYPE: postgres
  #     SERVICE_NAME: metastore  

  # metastore-db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: metastore
  #     POSTGRES_USER: hive
  #     POSTGRES_PASSWORD: hivepass
  #   volumes:
  #     - ./metastore-data:/var/lib/postgresql/data

  # trino:
  #   image: trinodb/trino
  #   ports:
  #     - "8080:8080" # web 
  #   depends_on:
  #     - hive-metastore

  # metabase opcional
  # airflow-webserver
  # airflow-scheduler
  # airflor-db